//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrdersInfo = new HashSet<OrdersInfo>();
        }
    
        public int ProductId { get; set; }
        public string ItemNumber { get; set; }
        public string ProductName { get; set; }
        public int UnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SupplierId { get; set; }
        public int ProducerId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }

        public bool IsHighDiscount => this.Discount > 12;
        public bool IsOutOfStock => this.Count == 0 || this.Count == null;
        public decimal ActualPrice
        {
            get
            {
                if (this.Discount == 0 || this.Discount == null)
                {
                    return this.Price ?? 0;
                }
                decimal discountPercent = (decimal)this.Discount / 100;
                decimal totalPrice = (this.Price ?? 0) * (1 - discountPercent);
                return Math.Round(totalPrice, 2);
            }
        }

        public string ImagePath
        {
            get
            {
                string photoName = string.IsNullOrEmpty(this.Photo) ? "picture.png" : this.Photo.Trim();

                string fullPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Images", photoName);

                return new Uri(fullPath).AbsoluteUri;
            }
        }

        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersInfo> OrdersInfo { get; set; }
        public virtual Producers Producers { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Units Units { get; set; }
    }
}
